import { Inter } from "next/font/google";
import "./globals.css";
import "@primer/octicons/index.scss";
import { SiteContextProvider } from "../context/SiteContext";
import { ToolCallHeader, ToolCallContainer } from "../components/ui";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <SiteContextProvider>
          <ToolCallContainer>
            <ToolCallHeader
              status="In progress"
              duration="1s"
              triggeredInfo="Triggered via issue"
              triggerUser="mayagao"
            />
            <div
              style={{
                backgroundColor: "#f6f8fa",
              }}
              className="px-8  py-4 pb-12 rounded-b-lg"
            >
              {children}
            </div>
          </ToolCallContainer>
        </SiteContextProvider>
      </body>
    </html>
  );
}
