import { Inter, Inter as InterMono } from "next/font/google";
import "./globals.css";
import "@primer/octicons/index.scss";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const interMono = InterMono({
  variable: "--font-inter-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${interMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
